import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';
import { createActionsService } from './actions-service.js';

const SAMPLE_ENVIRONMENT = `# THIS IS AUTOGENERATED. DO NOT EDIT MANUALLY
version = 1
name = "CodexMobile"

[setup]
script = ""

[[actions]]
name = "构建"
icon = "run"
command = "npm run build"

[[actions]]
name = "运行并启动tailscale"
icon = "run"
command = '''
tailscale serve --bg 3321
pm2 start ecosystem.config.cjs
'''
platform = "win32"

[[actions]]
name = "后台运行codemobile"
icon = "run"
command = "pm2 start ecosystem.config.cjs"
`;

async function withProject(files = {}, fn) {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), 'codexmobile-actions-'));
  const project = { id: 'project-1', name: 'CodexMobile', path: root };
  try {
    for (const [relativePath, content] of Object.entries(files)) {
      const filePath = path.join(root, relativePath);
      await fs.mkdir(path.dirname(filePath), { recursive: true });
      await fs.writeFile(filePath, content, 'utf8');
    }
    await fn({
      root,
      project,
      envPath: path.join(root, '.codex', 'environments', 'environment.toml')
    });
  } finally {
    await fs.rm(root, { recursive: true, force: true });
  }
}

function createService(project, overrides = {}) {
  return createActionsService({
    getProject(projectId) {
      return projectId === project.id ? project : null;
    },
    ...overrides
  });
}

test('actions service reads the current environment.toml and reports platform matching', async () => {
  await withProject({
    '.codex/environments/environment.toml': SAMPLE_ENVIRONMENT
  }, async ({ project, envPath }) => {
    const service = createService(project, { runtimePlatform: 'linux' });
    const result = await service.getEnvironment(project.id);

    assert.equal(result.exists, true);
    assert.equal(result.path, envPath);
    assert.ok(result.revision);
    assert.equal(result.environment.name, 'CodexMobile');
    assert.equal(result.environment.setupScriptPresent, false);
    assert.equal(result.environment.actions.length, 3);
    assert.equal(result.environment.actions[0].name, '构建');
    assert.equal(result.environment.actions[1].platform, 'win32');
    assert.equal(result.environment.actions[1].platformMatched, false);
    assert.match(result.environment.actions[1].command, /tailscale serve --bg 3321/);
  });
});

test('actions service creates the file on first add and preserves setup through update and delete', async () => {
  await withProject({}, async ({ project, envPath }) => {
    const service = createService(project, { runtimePlatform: 'win32' });
    const initial = await service.getEnvironment(project.id);
    assert.equal(initial.exists, false);
    assert.equal(initial.environment.actions.length, 0);

    const created = await service.createAction(project.id, initial.revision, {
      name: '构建',
      icon: 'run',
      command: 'npm run build',
      platform: 'all'
    });
    assert.equal(created.exists, true);
    assert.equal(created.environment.actions.length, 1);
    assert.equal(created.environment.actions[0].platform, null);

    const createdAction = created.environment.actions[0];
    const multiLineCommand = 'npm run build\nnpm run test';
    const updated = await service.updateAction(project.id, created.revision, createdAction.actionKey, {
      name: '后台构建',
      icon: 'run',
      command: multiLineCommand,
      platform: 'win32'
    });
    assert.equal(updated.environment.actions[0].name, '后台构建');
    assert.equal(updated.environment.actions[0].platform, 'win32');
    assert.equal(updated.environment.actions[0].command, multiLineCommand);

    const removed = await service.deleteAction(project.id, updated.revision, updated.environment.actions[0].actionKey);
    assert.equal(removed.environment.actions.length, 0);

    const written = await fs.readFile(envPath, 'utf8');
    assert.match(written, /\[setup\]/);
    assert.match(written, /script = ""/);
    assert.doesNotMatch(written, /\[\[actions\]\]/);
  });
});

test('actions service rejects stale revisions after the file changes on disk', async () => {
  await withProject({
    '.codex/environments/environment.toml': SAMPLE_ENVIRONMENT
  }, async ({ project, envPath }) => {
    const service = createService(project, { runtimePlatform: 'win32' });
    const initial = await service.getEnvironment(project.id);
    await fs.writeFile(envPath, `${SAMPLE_ENVIRONMENT}\n# changed\n`, 'utf8');

    await assert.rejects(
      service.createAction(project.id, initial.revision, {
        name: '测试',
        icon: 'run',
        command: 'npm test',
        platform: 'all'
      }),
      (error) => error?.statusCode === 409 && /已变更/.test(error.message)
    );
  });
});

test('actions service surfaces invalid TOML instead of overwriting it', async () => {
  await withProject({
    '.codex/environments/environment.toml': 'name = "broken\n'
  }, async ({ project }) => {
    const service = createService(project);

    await assert.rejects(
      service.getEnvironment(project.id),
      (error) => error?.statusCode === 422 && /未闭合/.test(error.message)
    );
  });
});

test('actions service blocks runs on mismatched platforms', async () => {
  await withProject({
    '.codex/environments/environment.toml': SAMPLE_ENVIRONMENT
  }, async ({ project }) => {
    const service = createService(project, { runtimePlatform: 'linux' });
    const snapshot = await service.getEnvironment(project.id);
    const target = snapshot.environment.actions.find((action) => action.platform === 'win32');

    await assert.rejects(
      service.runAction(project.id, target.actionKey),
      (error) => error?.statusCode === 409 && /当前平台 linux/.test(error.message)
    );
  });
});

test('actions service runs commands in project cwd and enforces one in-flight action per project', async () => {
  await withProject({
    '.codex/environments/environment.toml': SAMPLE_ENVIRONMENT
  }, async ({ project, root }) => {
    let resolveRun = null;
    let startRun = null;
    const started = new Promise((resolve) => {
      startRun = resolve;
    });
    const calls = [];
    const service = createService(project, {
      runtimePlatform: 'win32',
      runCommand(command, options) {
        calls.push({ command, options });
        startRun();
        return new Promise((resolve) => {
          resolveRun = resolve;
        });
      }
    });
    const snapshot = await service.getEnvironment(project.id);
    const actionKey = snapshot.environment.actions[0].actionKey;

    const firstRun = service.runAction(project.id, actionKey);
    await started;

    await assert.rejects(
      service.runAction(project.id, actionKey),
      (error) => error?.statusCode === 409 && /已有 action 正在运行/.test(error.message)
    );

    resolveRun({
      exitCode: 0,
      signal: null,
      stdout: 'done',
      stderr: '',
      timedOut: false,
      truncated: false,
      durationMs: 8
    });
    const result = await firstRun;

    assert.equal(calls.length, 1);
    assert.equal(calls[0].command, 'npm run build');
    assert.equal(calls[0].options.cwd, root);
    assert.equal(result.stdout, 'done');
    assert.equal(result.exitCode, 0);
  });
});
