import { spawn } from 'node:child_process';
import { createHash } from 'node:crypto';
import fs from 'node:fs/promises';
import path from 'node:path';

const ACTIONS_RELATIVE_PATH = path.join('.codex', 'environments', 'environment.toml');
const DEFAULT_HEADER = '# THIS IS AUTOGENERATED. DO NOT EDIT MANUALLY';
const DEFAULT_VERSION = 1;
const DEFAULT_TIMEOUT_MS = 10 * 60 * 1000;
const DEFAULT_MAX_OUTPUT_BYTES = 1024 * 1024;
const SUPPORTED_PLATFORMS = new Set(['win32', 'darwin', 'linux']);
const MANAGED_ACTION_KEYS = new Set(['name', 'icon', 'command', 'platform']);

function serviceError(message, statusCode = 500) {
  const error = new Error(message);
  error.statusCode = statusCode;
  return error;
}

function hashText(value = '') {
  return createHash('sha256').update(String(value || ''), 'utf8').digest('hex');
}

export function revisionForSource(source = null, filePath = '') {
  if (source === null) {
    return hashText(`missing\0${path.resolve(String(filePath || '.'))}`);
  }
  return hashText(`present\0${String(source)}`);
}

function isCommentTail(value = '') {
  const trimmed = String(value || '').trim();
  return !trimmed || trimmed.startsWith('#');
}

function stripInlineComment(value = '') {
  const index = String(value || '').indexOf('#');
  return index === -1 ? String(value || '') : String(value || '').slice(0, index);
}

function assertCommentTail(value, lineNumber) {
  if (!isCommentTail(value)) {
    throw serviceError(`environment.toml 第 ${lineNumber} 行存在不支持的尾随内容`, 422);
  }
}

function parseBareValue(value, lineNumber) {
  const trimmed = stripInlineComment(value).trim();
  if (!trimmed) {
    throw serviceError(`environment.toml 第 ${lineNumber} 行缺少值`, 422);
  }
  if (/^[+-]?\d+$/.test(trimmed)) {
    return Number.parseInt(trimmed, 10);
  }
  if (trimmed === 'true') {
    return true;
  }
  if (trimmed === 'false') {
    return false;
  }
  throw serviceError(`environment.toml 第 ${lineNumber} 行使用了不支持的 TOML 值`, 422);
}

function unescapeBasicString(content, lineNumber, { multiline = false } = {}) {
  let value = '';
  for (let index = 0; index < content.length; index += 1) {
    const char = content[index];
    if (char !== '\\') {
      value += char;
      continue;
    }
    const next = content[index + 1];
    if (multiline && next === '\n') {
      index += 1;
      while (index + 1 < content.length && /[ \t\r\n]/.test(content[index + 1])) {
        index += 1;
      }
      continue;
    }
    if (!next) {
      throw serviceError(`environment.toml 第 ${lineNumber} 行字符串转义不完整`, 422);
    }
    index += 1;
    if (next === 'b') value += '\b';
    else if (next === 't') value += '\t';
    else if (next === 'n') value += '\n';
    else if (next === 'f') value += '\f';
    else if (next === 'r') value += '\r';
    else if (next === '"') value += '"';
    else if (next === '\\') value += '\\';
    else if (next === 'u' || next === 'U') {
      const length = next === 'u' ? 4 : 8;
      const hex = content.slice(index + 1, index + 1 + length);
      if (!/^[0-9a-fA-F]+$/.test(hex) || hex.length !== length) {
        throw serviceError(`environment.toml 第 ${lineNumber} 行 Unicode 转义非法`, 422);
      }
      value += String.fromCodePoint(Number.parseInt(hex, 16));
      index += length;
    } else {
      throw serviceError(`environment.toml 第 ${lineNumber} 行包含不支持的转义`, 422);
    }
  }
  return value;
}

function parseSingleLiteral(value, lineNumber) {
  const text = String(value || '');
  const endIndex = text.indexOf('\'', 1);
  if (endIndex === -1) {
    throw serviceError(`environment.toml 第 ${lineNumber} 行字符串未闭合`, 422);
  }
  assertCommentTail(text.slice(endIndex + 1), lineNumber);
  return {
    value: text.slice(1, endIndex),
    nextIndex: null
  };
}

function parseSingleBasic(value, lineNumber) {
  const text = String(value || '');
  let escaped = false;
  for (let index = 1; index < text.length; index += 1) {
    const char = text[index];
    if (!escaped && char === '"') {
      assertCommentTail(text.slice(index + 1), lineNumber);
      return {
        value: unescapeBasicString(text.slice(1, index), lineNumber),
        nextIndex: null
      };
    }
    escaped = !escaped && char === '\\';
    if (escaped && index === text.length - 1) {
      throw serviceError(`environment.toml 第 ${lineNumber} 行字符串转义不完整`, 422);
    }
    if (char !== '\\') {
      escaped = false;
    }
  }
  throw serviceError(`environment.toml 第 ${lineNumber} 行字符串未闭合`, 422);
}

function parseMultilineLiteral(lines, startIndex, value, lineNumber) {
  const remainder = String(value || '').slice(3);
  const closingInFirstLine = remainder.indexOf('\'\'\'');
  if (closingInFirstLine !== -1) {
    assertCommentTail(remainder.slice(closingInFirstLine + 3), lineNumber);
    return {
      value: remainder.slice(0, closingInFirstLine),
      nextIndex: startIndex + 1
    };
  }

  const parts = [];
  if (remainder) {
    parts.push(remainder);
  }
  for (let index = startIndex + 1; index < lines.length; index += 1) {
    const line = lines[index];
    const closingIndex = line.indexOf('\'\'\'');
    if (closingIndex === -1) {
      parts.push(line);
      continue;
    }
    parts.push(line.slice(0, closingIndex));
    assertCommentTail(line.slice(closingIndex + 3), index + 1);
    return {
      value: parts.join('\n'),
      nextIndex: index + 1
    };
  }
  throw serviceError(`environment.toml 第 ${lineNumber} 行多行字符串未闭合`, 422);
}

function findClosingTripleQuote(value, quote = '"') {
  for (let index = 0; index <= value.length - 3; index += 1) {
    if (value[index] !== quote || value[index + 1] !== quote || value[index + 2] !== quote) {
      continue;
    }
    let slashCount = 0;
    for (let cursor = index - 1; cursor >= 0 && value[cursor] === '\\'; cursor -= 1) {
      slashCount += 1;
    }
    if (slashCount % 2 === 0) {
      return index;
    }
  }
  return -1;
}

function parseMultilineBasic(lines, startIndex, value, lineNumber) {
  const remainder = String(value || '').slice(3);
  const closingInFirstLine = findClosingTripleQuote(remainder);
  if (closingInFirstLine !== -1) {
    assertCommentTail(remainder.slice(closingInFirstLine + 3), lineNumber);
    return {
      value: unescapeBasicString(remainder.slice(0, closingInFirstLine), lineNumber, { multiline: true }),
      nextIndex: startIndex + 1
    };
  }

  const parts = [];
  if (remainder) {
    parts.push(remainder);
  }
  for (let index = startIndex + 1; index < lines.length; index += 1) {
    const line = lines[index];
    const closingIndex = findClosingTripleQuote(line);
    if (closingIndex === -1) {
      parts.push(line);
      continue;
    }
    parts.push(line.slice(0, closingIndex));
    assertCommentTail(line.slice(closingIndex + 3), index + 1);
    return {
      value: unescapeBasicString(parts.join('\n'), lineNumber, { multiline: true }),
      nextIndex: index + 1
    };
  }
  throw serviceError(`environment.toml 第 ${lineNumber} 行多行字符串未闭合`, 422);
}

function parseTomlValue(lines, startIndex, value, lineNumber) {
  const trimmed = String(value || '').trimStart();
  if (trimmed.startsWith('\'\'\'')) {
    return parseMultilineLiteral(lines, startIndex, trimmed, lineNumber);
  }
  if (trimmed.startsWith('"""')) {
    return parseMultilineBasic(lines, startIndex, trimmed, lineNumber);
  }
  if (trimmed.startsWith('\'')) {
    const parsed = parseSingleLiteral(trimmed, lineNumber);
    return { ...parsed, nextIndex: startIndex + 1 };
  }
  if (trimmed.startsWith('"')) {
    const parsed = parseSingleBasic(trimmed, lineNumber);
    return { ...parsed, nextIndex: startIndex + 1 };
  }
  return {
    value: parseBareValue(trimmed, lineNumber),
    nextIndex: startIndex + 1
  };
}

function parseHeader(line, lineNumber) {
  const head = stripInlineComment(line).trim();
  const arrayMatch = head.match(/^\[\[\s*([A-Za-z0-9_.-]+)\s*\]\]$/);
  if (arrayMatch) {
    return { kind: 'array', name: arrayMatch[1] };
  }
  const tableMatch = head.match(/^\[\s*([A-Za-z0-9_.-]+)\s*\]$/);
  if (tableMatch) {
    return { kind: 'table', name: tableMatch[1] };
  }
  throw serviceError(`environment.toml 第 ${lineNumber} 行表头非法`, 422);
}

function pushEntry(entries, key, value, lineNumber) {
  if (!/^[A-Za-z0-9_-]+$/.test(key)) {
    throw serviceError(`environment.toml 第 ${lineNumber} 行键名非法`, 422);
  }
  if (entries.some((entry) => entry.key === key)) {
    throw serviceError(`environment.toml 第 ${lineNumber} 行存在重复键 ${key}`, 422);
  }
  entries.push({ key, value });
}

export function parseEnvironmentToml(source = '') {
  const lines = String(source || '').replace(/\r\n/g, '\n').split('\n');
  const headerLines = [];
  const rootEntries = [];
  const sections = [];
  const seenTables = new Set();
  let currentEntries = rootEntries;
  let seenContent = false;

  for (let index = 0; index < lines.length;) {
    const line = lines[index];
    const trimmed = line.trim();
    const lineNumber = index + 1;

    if (!trimmed) {
      index += 1;
      continue;
    }

    if (trimmed.startsWith('#')) {
      if (!seenContent && !rootEntries.length && !sections.length) {
        headerLines.push(trimmed);
      }
      index += 1;
      continue;
    }

    seenContent = true;
    if (trimmed.startsWith('[')) {
      const header = parseHeader(line, lineNumber);
      if (header.kind === 'table') {
        if (seenTables.has(header.name)) {
          throw serviceError(`environment.toml 第 ${lineNumber} 行重复定义表 ${header.name}`, 422);
        }
        seenTables.add(header.name);
      }
      const section = { kind: header.kind, name: header.name, entries: [] };
      sections.push(section);
      currentEntries = section.entries;
      index += 1;
      continue;
    }

    const separator = line.indexOf('=');
    if (separator === -1) {
      throw serviceError(`environment.toml 第 ${lineNumber} 行缺少 =`, 422);
    }
    const key = line.slice(0, separator).trim();
    const value = line.slice(separator + 1).trimStart();
    const parsed = parseTomlValue(lines, index, value, lineNumber);
    pushEntry(currentEntries, key, parsed.value, lineNumber);
    index = parsed.nextIndex;
  }

  return {
    headerLines,
    rootEntries,
    sections
  };
}

function cloneEntries(entries = []) {
  return entries.map((entry) => ({ key: entry.key, value: entry.value }));
}

function cloneDocument(document) {
  return {
    headerLines: [...(document.headerLines || [])],
    rootEntries: cloneEntries(document.rootEntries),
    sections: (document.sections || []).map((section) => ({
      kind: section.kind,
      name: section.name,
      entries: cloneEntries(section.entries)
    }))
  };
}

function findEntry(entries, key) {
  return (entries || []).find((entry) => entry.key === key) || null;
}

function ensureSetupSection(document) {
  const existing = document.sections.find((section) => section.kind === 'table' && section.name === 'setup');
  if (existing) {
    if (!findEntry(existing.entries, 'script')) {
      existing.entries.push({ key: 'script', value: '' });
    }
    return existing;
  }
  const section = {
    kind: 'table',
    name: 'setup',
    entries: [{ key: 'script', value: '' }]
  };
  const insertIndex = document.sections.findIndex((item) => item.kind === 'array' && item.name === 'actions');
  if (insertIndex === -1) {
    document.sections.push(section);
  } else {
    document.sections.splice(insertIndex, 0, section);
  }
  return section;
}

function normalizeDocumentDefaults(document, projectName = 'Project') {
  const name = String(projectName || 'Project').trim() || 'Project';
  const versionEntry = findEntry(document.rootEntries, 'version');
  if (!versionEntry || typeof versionEntry.value !== 'number') {
    if (versionEntry) {
      versionEntry.value = DEFAULT_VERSION;
    } else {
      document.rootEntries.unshift({ key: 'version', value: DEFAULT_VERSION });
    }
  }

  const nameEntry = findEntry(document.rootEntries, 'name');
  if (!nameEntry || typeof nameEntry.value !== 'string' || !nameEntry.value.trim()) {
    if (nameEntry) {
      nameEntry.value = name;
    } else {
      const versionIndex = document.rootEntries.findIndex((entry) => entry.key === 'version');
      const insertAt = versionIndex === -1 ? 0 : versionIndex + 1;
      document.rootEntries.splice(insertAt, 0, { key: 'name', value: name });
    }
  }

  ensureSetupSection(document);
  return document;
}

function escapeBasicString(value = '') {
  return String(value || '')
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\u0008/g, '\\b')
    .replace(/\t/g, '\\t')
    .replace(/\f/g, '\\f')
    .replace(/\r/g, '\\r')
    .replace(/\n/g, '\\n');
}

function escapeMultilineBasicString(value = '') {
  return String(value || '')
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\u0008/g, '\\b')
    .replace(/\t/g, '\\t')
    .replace(/\f/g, '\\f')
    .replace(/\r/g, '\\r');
}

function serializeTomlValue(value) {
  if (typeof value === 'number' && Number.isInteger(value)) {
    return String(value);
  }
  if (typeof value === 'boolean') {
    return value ? 'true' : 'false';
  }
  if (typeof value === 'string') {
    if (value.includes('\n')) {
      if (!value.includes('\'\'\'')) {
        return `'''${value}'''`;
      }
      return `"""${escapeMultilineBasicString(value)}"""`;
    }
    return `"${escapeBasicString(value)}"`;
  }
  throw serviceError('存在不支持的 TOML 值类型，无法写回 environment.toml', 500);
}

export function serializeEnvironmentToml(document, { defaultHeader = DEFAULT_HEADER } = {}) {
  const headerLines = Array.isArray(document.headerLines) && document.headerLines.length
    ? document.headerLines
    : [defaultHeader];
  const lines = [...headerLines];
  const rootEntries = Array.isArray(document.rootEntries) ? document.rootEntries : [];
  const sections = Array.isArray(document.sections) ? document.sections : [];

  if (rootEntries.length) {
    lines.push('');
    for (const entry of rootEntries) {
      lines.push(`${entry.key} = ${serializeTomlValue(entry.value)}`);
    }
  }

  for (const section of sections) {
    lines.push('');
    lines.push(section.kind === 'array' ? `[[${section.name}]]` : `[${section.name}]`);
    for (const entry of section.entries || []) {
      lines.push(`${entry.key} = ${serializeTomlValue(entry.value)}`);
    }
  }

  return `${lines.join('\n')}\n`;
}

function actionEntries(section) {
  const entries = Array.isArray(section?.entries) ? section.entries : [];
  const name = findEntry(entries, 'name')?.value;
  const icon = findEntry(entries, 'icon')?.value;
  const command = findEntry(entries, 'command')?.value;
  const platform = findEntry(entries, 'platform')?.value ?? null;

  if (typeof name !== 'string' || !name.trim()) {
    throw serviceError('environment.toml 中存在缺少 name 的 action', 422);
  }
  if (typeof icon !== 'string' || !icon.trim()) {
    throw serviceError('environment.toml 中存在缺少 icon 的 action', 422);
  }
  if (typeof command !== 'string' || !command.trim()) {
    throw serviceError('environment.toml 中存在缺少 command 的 action', 422);
  }
  if (platform !== null && typeof platform !== 'string') {
    throw serviceError('environment.toml 中存在非法 platform 字段', 422);
  }

  return {
    name: name.trim(),
    icon: icon.trim(),
    command,
    platform: platform ? String(platform).trim() || null : null
  };
}

function actionKeyFor(section, index) {
  const digest = hashText(JSON.stringify(section.entries || [])).slice(0, 12);
  return `${index}:${digest}`;
}

function platformMatched(platform, runtimePlatform = process.platform) {
  return !platform || platform === runtimePlatform;
}

function environmentFromDocument(document, runtimePlatform = process.platform) {
  const rootEntries = document.rootEntries || [];
  const version = findEntry(rootEntries, 'version')?.value ?? DEFAULT_VERSION;
  const name = findEntry(rootEntries, 'name')?.value ?? '';
  const setupSection = document.sections.find((section) => section.kind === 'table' && section.name === 'setup') || null;
  const setupScript = setupSection ? String(findEntry(setupSection.entries, 'script')?.value ?? '') : '';
  const actionSections = document.sections.filter((section) => section.kind === 'array' && section.name === 'actions');

  return {
    version: typeof version === 'number' ? version : DEFAULT_VERSION,
    name: typeof name === 'string' ? name : '',
    setupScript,
    setupScriptPresent: Boolean(setupScript.trim()),
    actions: actionSections.map((section, index) => {
      const action = actionEntries(section);
      return {
        actionKey: actionKeyFor(section, index),
        index,
        name: action.name,
        icon: action.icon,
        command: action.command,
        platform: action.platform,
        platformMatched: platformMatched(action.platform, runtimePlatform)
      };
    })
  };
}

function defaultDocument(projectName = 'Project') {
  return normalizeDocumentDefaults({
    headerLines: [DEFAULT_HEADER],
    rootEntries: [],
    sections: []
  }, projectName);
}

function normalizePlatformInput(value) {
  const platformValue = String(value || '').trim();
  if (!platformValue || platformValue === 'all') {
    return null;
  }
  if (!SUPPORTED_PLATFORMS.has(platformValue)) {
    throw serviceError('platform 仅支持 win32、darwin、linux 或 all', 400);
  }
  return platformValue;
}

function normalizeActionInput(payload = {}) {
  const name = String(payload.name || '').trim();
  const icon = String(payload.icon || '').trim();
  const command = String(payload.command ?? '');
  if (!name) {
    throw serviceError('Action name is required', 400);
  }
  if (!icon) {
    throw serviceError('Action icon is required', 400);
  }
  if (!command.trim()) {
    throw serviceError('Action command is required', 400);
  }
  return {
    name,
    icon,
    command,
    platform: normalizePlatformInput(payload.platform)
  };
}

function actionSectionFromInput(action, existingSection = null) {
  const extras = existingSection
    ? existingSection.entries.filter((entry) => !MANAGED_ACTION_KEYS.has(entry.key)).map((entry) => ({ key: entry.key, value: entry.value }))
    : [];
  const entries = [
    { key: 'name', value: action.name },
    { key: 'icon', value: action.icon },
    { key: 'command', value: action.command }
  ];
  if (action.platform) {
    entries.push({ key: 'platform', value: action.platform });
  }
  return {
    kind: 'array',
    name: 'actions',
    entries: [...entries, ...extras]
  };
}

function replaceActionSections(document, sections) {
  const result = [];
  let inserted = false;
  let actionFound = false;
  let insertAfterSetupIndex = -1;

  for (const section of document.sections) {
    if (section.kind === 'table' && section.name === 'setup') {
      insertAfterSetupIndex = result.length;
    }
    if (section.kind === 'array' && section.name === 'actions') {
      actionFound = true;
      if (!inserted) {
        result.push(...sections);
        inserted = true;
      }
      continue;
    }
    result.push(section);
  }

  if (inserted) {
    document.sections = result;
    return document;
  }

  if (!actionFound && sections.length) {
    const insertIndex = insertAfterSetupIndex === -1 ? result.length : insertAfterSetupIndex + 1;
    result.splice(insertIndex, 0, ...sections);
  }
  document.sections = result;
  return document;
}

function locateActionSection(document, actionKey) {
  const actions = document.sections
    .map((section, sectionIndex) => ({ section, sectionIndex }))
    .filter(({ section }) => section.kind === 'array' && section.name === 'actions');
  const actionIndex = actions.findIndex(({ section }, index) => actionKeyFor(section, index) === actionKey);
  if (actionIndex === -1) {
    return null;
  }
  return {
    ...actions[actionIndex],
    actionIndex
  };
}

async function defaultCommandRunner(command, options = {}) {
  const timeoutMs = Math.max(1000, Number(options.timeoutMs) || DEFAULT_TIMEOUT_MS);
  const maxOutputBytes = Math.max(1024, Number(options.maxOutputBytes) || DEFAULT_MAX_OUTPUT_BYTES);
  const startedAt = Date.now();
  const isWindows = process.platform === 'win32';
  const executable = isWindows ? 'powershell.exe' : '/bin/sh';
  const args = isWindows
    ? ['-NoProfile', '-NonInteractive', '-ExecutionPolicy', 'Bypass', '-Command', command]
    : ['-lc', command];

  return new Promise((resolve, reject) => {
    const child = spawn(executable, args, {
      cwd: options.cwd,
      env: process.env,
      stdio: ['ignore', 'pipe', 'pipe'],
      windowsHide: true
    });

    let stdout = '';
    let stderr = '';
    let combinedBytes = 0;
    let truncated = false;
    let timedOut = false;
    let settled = false;
    const killTimer = setTimeout(() => {
      timedOut = true;
      child.kill();
      setTimeout(() => child.kill('SIGKILL'), 2000).unref?.();
    }, timeoutMs);
    killTimer.unref?.();

    const append = (target, chunk) => {
      const text = String(chunk || '');
      if (!text) {
        return target;
      }
      const remaining = maxOutputBytes - combinedBytes;
      const bufferSize = Buffer.byteLength(text);
      combinedBytes += bufferSize;
      if (remaining <= 0) {
        truncated = true;
        return target;
      }
      if (bufferSize > remaining) {
        truncated = true;
        return target + text.slice(0, remaining);
      }
      return target + text;
    };

    child.stdout.on('data', (chunk) => {
      stdout = append(stdout, chunk);
    });
    child.stderr.on('data', (chunk) => {
      stderr = append(stderr, chunk);
    });
    child.on('error', (error) => {
      if (settled) {
        return;
      }
      settled = true;
      clearTimeout(killTimer);
      reject(serviceError(error.message || 'Action command failed to start', 500));
    });
    child.on('close', (exitCode, signal) => {
      if (settled) {
        return;
      }
      settled = true;
      clearTimeout(killTimer);
      resolve({
        exitCode: typeof exitCode === 'number' ? exitCode : null,
        signal: signal || null,
        stdout,
        stderr,
        timedOut,
        truncated,
        durationMs: Date.now() - startedAt
      });
    });
  });
}

function normalizeProjectName(project, cwd) {
  return String(project?.name || '').trim() || path.basename(String(cwd || '')) || 'Project';
}

async function readSource(fsModule, filePath) {
  try {
    return {
      exists: true,
      source: await fsModule.readFile(filePath, 'utf8')
    };
  } catch (error) {
    if (error.code === 'ENOENT') {
      return {
        exists: false,
        source: null
      };
    }
    throw error;
  }
}

export function createActionsService({
  getProject,
  fsModule = fs,
  runCommand = defaultCommandRunner,
  timeoutMs = DEFAULT_TIMEOUT_MS,
  maxOutputBytes = DEFAULT_MAX_OUTPUT_BYTES,
  runtimePlatform = process.platform
} = {}) {
  if (typeof getProject !== 'function') {
    throw new Error('createActionsService requires getProject');
  }

  const runningByProject = new Map();

  async function resolveProjectContext(projectId) {
    const normalizedProjectId = String(projectId || '').trim();
    if (!normalizedProjectId) {
      throw serviceError('projectId is required', 400);
    }
    const project = getProject(normalizedProjectId);
    if (!project?.path) {
      throw serviceError('Project not found', 404);
    }
    const cwd = path.resolve(project.path);
    const envPath = path.resolve(cwd, ACTIONS_RELATIVE_PATH);
    const projectPrefix = cwd.endsWith(path.sep) ? cwd : `${cwd}${path.sep}`;
    if (envPath !== cwd && !envPath.startsWith(projectPrefix)) {
      throw serviceError('Environment path escapes project root', 400);
    }
    try {
      const stat = await fsModule.stat(cwd);
      if (!stat.isDirectory()) {
        throw serviceError('Project path is not a directory', 409);
      }
    } catch (error) {
      if (error.statusCode) {
        throw error;
      }
      if (error.code === 'ENOENT') {
        throw serviceError('Project path not found', 404);
      }
      throw error;
    }
    return {
      projectId: normalizedProjectId,
      project,
      cwd,
      envPath,
      projectName: normalizeProjectName(project, cwd)
    };
  }

  function payloadForDocument(document, context, exists, revision) {
    const normalized = normalizeDocumentDefaults(cloneDocument(document), context.projectName);
    return {
      exists,
      path: context.envPath,
      revision,
      environment: environmentFromDocument(normalized, runtimePlatform)
    };
  }

  async function load(projectId) {
    const context = await resolveProjectContext(projectId);
    const current = await readSource(fsModule, context.envPath);
    if (!current.exists) {
      const revision = revisionForSource(null, context.envPath);
      return {
        context,
        exists: false,
        revision,
        document: defaultDocument(context.projectName),
        source: null,
        payload: payloadForDocument(defaultDocument(context.projectName), context, false, revision)
      };
    }
    const document = normalizeDocumentDefaults(parseEnvironmentToml(current.source), context.projectName);
    const revision = revisionForSource(current.source, context.envPath);
    return {
      context,
      exists: true,
      revision,
      document,
      source: current.source,
      payload: payloadForDocument(document, context, true, revision)
    };
  }

  async function persist(context, expectedRevision, document) {
    const current = await readSource(fsModule, context.envPath);
    const currentRevision = revisionForSource(current.exists ? current.source : null, context.envPath);
    if (currentRevision !== String(expectedRevision || '')) {
      throw serviceError('environment.toml 已变更，请刷新后重试', 409);
    }
    await fsModule.mkdir(path.dirname(context.envPath), { recursive: true });
    const normalized = normalizeDocumentDefaults(cloneDocument(document), context.projectName);
    const nextSource = serializeEnvironmentToml(normalized);
    await fsModule.writeFile(context.envPath, nextSource, 'utf8');
    const revision = revisionForSource(nextSource, context.envPath);
    return payloadForDocument(normalized, context, true, revision);
  }

  async function getEnvironment(projectId) {
    const snapshot = await load(projectId);
    return snapshot.payload;
  }

  async function createAction(projectId, revision, actionInput) {
    const snapshot = await load(projectId);
    if (snapshot.revision !== String(revision || '')) {
      throw serviceError('environment.toml 已变更，请刷新后重试', 409);
    }
    const action = normalizeActionInput(actionInput);
    const nextDocument = cloneDocument(snapshot.document);
    const actionSections = nextDocument.sections.filter((section) => section.kind === 'array' && section.name === 'actions');
    const sections = [...actionSections.map((section) => ({ ...section, entries: cloneEntries(section.entries) })), actionSectionFromInput(action)];
    replaceActionSections(nextDocument, sections);
    return persist(snapshot.context, revision, nextDocument);
  }

  async function updateAction(projectId, revision, actionKey, actionInput) {
    const snapshot = await load(projectId);
    if (snapshot.revision !== String(revision || '')) {
      throw serviceError('environment.toml 已变更，请刷新后重试', 409);
    }
    const action = normalizeActionInput(actionInput);
    const nextDocument = cloneDocument(snapshot.document);
    const target = locateActionSection(nextDocument, String(actionKey || '').trim());
    if (!target) {
      throw serviceError('Action 已变更或不存在，请刷新后重试', 409);
    }
    nextDocument.sections[target.sectionIndex] = actionSectionFromInput(action, target.section);
    return persist(snapshot.context, revision, nextDocument);
  }

  async function deleteAction(projectId, revision, actionKey) {
    const snapshot = await load(projectId);
    if (snapshot.revision !== String(revision || '')) {
      throw serviceError('environment.toml 已变更，请刷新后重试', 409);
    }
    const nextDocument = cloneDocument(snapshot.document);
    const target = locateActionSection(nextDocument, String(actionKey || '').trim());
    if (!target) {
      throw serviceError('Action 已变更或不存在，请刷新后重试', 409);
    }
    nextDocument.sections.splice(target.sectionIndex, 1);
    return persist(snapshot.context, revision, nextDocument);
  }

  async function runAction(projectId, actionKey) {
    const snapshot = await load(projectId);
    const target = locateActionSection(snapshot.document, String(actionKey || '').trim());
    if (!target) {
      throw serviceError('Action not found', 404);
    }
    const action = actionEntries(target.section);
    if (!platformMatched(action.platform, runtimePlatform)) {
      throw serviceError(`当前平台 ${runtimePlatform} 不允许运行该 action`, 409);
    }
    if (runningByProject.has(snapshot.context.projectId)) {
      throw serviceError('当前项目已有 action 正在运行，请等待完成后重试', 409);
    }

    const lockToken = Symbol(snapshot.context.projectId);
    runningByProject.set(snapshot.context.projectId, {
      token: lockToken,
      actionKey: actionKeyFor(target.section, target.actionIndex),
      startedAt: new Date().toISOString()
    });

    try {
      const result = await runCommand(action.command, {
        cwd: snapshot.context.cwd,
        timeoutMs,
        maxOutputBytes
      });
      return {
        actionKey: actionKeyFor(target.section, target.actionIndex),
        name: action.name,
        icon: action.icon,
        command: action.command,
        platform: action.platform,
        platformMatched: true,
        cwd: snapshot.context.cwd,
        ...result
      };
    } finally {
      if (runningByProject.get(snapshot.context.projectId)?.token === lockToken) {
        runningByProject.delete(snapshot.context.projectId);
      }
    }
  }

  return {
    getEnvironment,
    createAction,
    updateAction,
    deleteAction,
    runAction
  };
}
